config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :listings, only: [:index, :show]

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'users', to: 'users#index'

  namespace :admin do
    resources :listings
    resources :brands
    resources :companies
    resources :deals
  end

  resource :profile, controller: :profile, only: [:show, :edit, :update]
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  slug            :string           not null
#  type            :string           not null
#  summary         :text
#  description     :text
#  street_address  :string
#  city            :string
#  state           :string
#  country         :string
#  website_url     :string
#  phone_number    :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  logo            :string
#  cover_photo     :string
#  thumbnail_photo :string
#

class Listing < ApplicationRecord
  self.inheritance_column = nil

  TYPES = [
    'Business',
    'Property',
    'People',
    'Groups',
    'Jobs and Ads'
  ]

  mount_uploader :logo, ListingLogoUploader
  mount_uploader :thumbnail_photo, ListingThumbnailPhotoUploader
  mount_uploader :cover_photo, ListingCoverPhotoUploader

  has_many :photos,
           class_name: ListingPhoto,
           inverse_of: :listing,
           dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  has_many :videos,
           class_name: ListingVideo,
           inverse_of: :listing,
           dependent: :destroy
  accepts_nested_attributes_for :videos, allow_destroy: true

  has_and_belongs_to_many :companies
  has_and_belongs_to_many :brands

  validates :name,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 2, maximum: 200 }
  validates :type, presence: true, inclusion: { in: TYPES }

  validates :website_url,
            url: true,
            allow_nil: true,
            allow_blank: true

  before_save :generate_slug, if: :name_changed?

  def full_address
    [street_address, city, state, country].compact.join(', ').strip
  end

  private

  def generate_slug
    self.slug = name.parameterize
  end
end

app/controllers/admin/listings_controller.rb
module Admin
  class ListingsController < BaseController
    before_action :set_listing, only: [:show, :edit, :update, :destroy]

    def index
      @listings = Listing.order(id: :desc).page(params[:page])
    end

    def show
    end

    def new
      @listing = Listing.new
    end

    def edit
    end

    def create
      @listing = Listing.new(listing_params)

      if @listing.save
        redirect_to admin_listing_path(@listing), notice: 'Listing was successfully created.'
      else
        render :new
      end
    end

    def update
      if @listing.update(listing_params)
        redirect_to admin_listing_path(@listing), notice: 'Listing was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @listing.destroy
      redirect_to admin_listings_url, notice: 'Listing was successfully destroyed.'
    end

    private

    def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(
        :name,
        :type,
        :summary,
        :description,
        :street_address,
        :city,
        :state,
        :country,
        :logo,
        :thumbnail_photo,
        :cover_photo,
        :website_url,
        :phone_number,
        :email,
        company_ids: [],
        brand_ids: [],
        photos_attributes: [:id, :caption, :image, :_destroy],
        videos_attributes: [:id, :caption, :url, :_destroy],
      )
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.order(id: :desc).all
  end

  def show
    @listing = Listing.find_by(slug: params[:id])
  end
end

app/views/admin/listings/_form.html.erb
<%= simple_nested_form_for @listing, url: (@listing.persisted? ? admin_listing_path(listing) : admin_listings_path), html: { novalidate: false } do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :name, required: true %>
      <%= f.input :company_ids, label: 'Companies', as: :select, include_hidden: false, collection: Company.select(:id, :name), input_html: { class: 'selectize', multiple: true } %>
      <%= f.input :brand_ids, label: 'Brands', as: :select, include_hidden: false, collection: Brand.select(:id, :name), input_html: { class: 'selectize', multiple: true } %>
      <%= f.input :type, as: :select, collection: Listing::TYPES, required: true %>
      <%= f.input :logo %>
      <%= f.input :thumbnail_photo %>
      <%= f.input :cover_photo %>
      <%= f.input :summary %>
      <%= f.input :description %>
      <%= f.input :website_url %>
      <%= f.input :phone_number %>
      <%= f.input :email %>
    </div>
    <div class="col-md-6">
      <div class="form-group" style="border: 1px solid #ccc; padding: 10px">
        <div class="form-group">
          <legend>Address</legend>
          <input class="form-control" type="text" id="input-full-address" placeholder="Enter a location to autocomplete address fields">
        </div>
        <%= f.input :street_address %>
        <%= f.input :city %>
        <%= f.input :state %>
        <%= f.input :country, as: :string %>
      </div>

      <div class="form-group" style="border: 1px solid #ccc; padding: 10px">
        <legend>Photos gallery</legend>
        <%= f.fields_for :photos do |photo_f|%>
          <div class="row">
            <div class="col-md-4">
              <%= photo_f.input :caption, label: false, placeholder: 'Caption' %>
            </div>
            <div class="col-md-5">
              <% if photo_f.object.image_url(:sm) %>
                <img src="<%= photo_f.object.image_url(:sm)%>" style="width: 50px">
              <% else %>
              <%= photo_f.input :image, label: false %>
              <% end %>
            </div>
            <div class="col-md-2">
              <%= photo_f.link_to_remove "Remove", class: 'text-danger' %>
            </div>
          </div>
        <% end %>
        <%= f.link_to_add "Add photo", :photos, class: 'btn btn-sm btn-default' %>
      </div>

      <div class="form-group" style="border: 1px solid #ccc; padding: 10px">
        <legend>Videos gallery</legend>
        <%= f.fields_for :videos do |video_f|%>
          <div class="row">
            <div class="col-md-4">
              <%= video_f.input :caption, label: false, placeholder: 'Caption' %>
            </div>
            <div class="col-md-5">
              <%= video_f.input :url, label: false, placeholder: 'URL' %>
            </div>
            <div class="col-md-2">
              <%= video_f.link_to_remove "Remove", class: 'text-danger' %>
            </div>
          </div>
        <% end %>
        <%= f.link_to_add "Add video", :videos, class: 'btn btn-sm btn-default' %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<% content_for :head_js do %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&libraries=places"></script>
<% end %>

<% content_for :page_js do %>
<script type="text/javascript">
  (function() {
    $(document).ready(function() {
      $('#input-full-address').on('keypress', function(e) {
        if (e.which === 13) {
          e.preventDefault();
        }
      });

      var fillInAddress = function(place) {
        var streetAddress = city = state = country = '';
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          var val = place.address_components[i].long_name;
          switch(addressType) {
            case 'street_number':
              streetAddress += val; break;
            case 'route':
              streetAddress += ' ' + val; break;
            case 'locality':
              city = val; break;
            case 'administrative_area_level_1':
              state = val; break;
            case 'country':
              country = val; break;
          }
        }

        $('[name="listing[street_address]"]').val(streetAddress.trim());
        $('[name="listing[city]"]').val(city);
        $('[name="listing[state]"]').val(state);
        $('[name="listing[country]"]').val(country);
      };

      var initAutocompleteAddress = function () {
        var autocomplete = new google.maps.places.Autocomplete(
          document.getElementById('input-full-address'),
          { types: ['geocode'] }
        );
        autocomplete.addListener('place_changed', function() {
          fillInAddress(autocomplete.getPlace());
        });
      };

      initAutocompleteAddress();
    });
  })();
</script>
<% end %>

app/views/admin/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>
<br>
<%= link_to 'Show', admin_listing_path(@listing) %> |
<%= link_to 'Back', admin_listings_path %>

app/views/admin/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manage Listings</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Brands</th>
      <th>Companies</th>
      <th>Summary</th>
      <th>Address</th>
      <th>Logo</th>
      <th>Thumbnail</th>
      <th>Cover</th>
      <th>Website url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.type %></td>
        <td><%= listing.brands.map(&:name).join(', ') %></td>
        <td><%= listing.companies.map(&:name).join(', ') %></td>
        <td><%= listing.summary %></td>
        <td><%= listing.full_address %></td>
        <td>
          <% if listing.logo_url %>
            <img src="<%= listing.logo_url %>" width="50">
          <% else %>
            N/A
          <% end %>
        </td>
        <td>
          <% if listing.thumbnail_photo_url %>
            <img src="<%= listing.thumbnail_photo_url %>" width="50">
          <% else %>
            N/A
          <% end %>
        </td>
        <td>
          <% if listing.cover_photo_url %>
            <img src="<%= listing.cover_photo_url %>" width="50">
          <% else %>
            N/A
          <% end %>
        </td>
        <td><%= listing.website_url %></td>
        <td><%= link_to 'Show', admin_listing_path(listing) %></td>
        <td><%= link_to 'Edit', edit_admin_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', admin_listing_path(listing), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="text-center">
  <%= page_entries_info @listings %>
  <br>
  <%= paginate @listings %>
</div>
<br>

<%= link_to 'New Listing', new_admin_listing_path %>

app/views/admin/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>
<br>
<%= link_to 'Back', admin_listings_path %>

app/views/admin/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Brands:</strong>
  <%= @listing.brands.map(&:name).join(', ') %>
</p>

<p>
  <strong>Companies:</strong>
  <%= @listing.companies.map(&:name).join(', ') %>
</p>

<p>
  <strong>Type:</strong>
  <%= @listing.type %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @listing.summary %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Street Address:</strong>
  <%= @listing.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @listing.country %>
</p>

<p>
  <strong>Logo:</strong>
  <% if @listing.logo_url %>
    <img src="<%= @listing.logo_url %>" width="50">
  <% else %>
    N/A
  <% end %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <% if @listing.thumbnail_photo_url %>
    <img src="<%= @listing.thumbnail_photo_url %>" width="50">
  <% else %>
    N/A
  <% end %>
</p>

<p>
  <strong>Cover:</strong>
  <% if @listing.cover_photo_url %>
    <img src="<%= @listing.cover_photo_url %>" width="50">
  <% else %>
    N/A
  <% end %>
</p>

<p>
  <strong>Website url:</strong>
  <%= @listing.website_url %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @listing.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @listing.email %>
</p>

<%= link_to 'Edit', edit_admin_listing_path(@listing) %> |
<%= link_to 'Back', admin_listings_path %>