config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :listings, only: [:index, :show]

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'users', to: 'users#index'

  namespace :admin do
    resources :listings
    resources :brands
    resources :companies
    resources :deals
  end

  resource :profile, controller: :profile, only: [:show, :edit, :update]
end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  summary         :text
#  description     :text
#  industry        :string
#  logo            :string
#  thumbnail_photo :string
#

class Brand < ApplicationRecord
  mount_uploader :logo, BrandLogoUploader
  mount_uploader :thumbnail_photo, BrandThumbnailPhotoUploader

  has_and_belongs_to_many :listings
  has_and_belongs_to_many :deals

  validates :name,
            presence: true,
            length: { minimum: 2, maximum: 100 }
end

app/controllers/admin/brands_controller.rb
module Admin
  class BrandsController < BaseController
    before_action :set_brand, only: [:show, :edit, :update, :destroy]

    def index
      @brands = Brand.order(id: :desc).page(params[:page])
    end

    def show
    end

    def new
      @brand = Brand.new
    end

    def edit
    end

    def create
      @brand = Brand.new(brand_params)

      if @brand.save
        redirect_to admin_brand_path(@brand), notice: 'Brand was successfully created.'
      else
        render :new
      end
    end

    def update
      if @brand.update(brand_params)
        redirect_to admin_brand_path(@brand), notice: 'Brand was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @brand.destroy
      redirect_to admin_brands_url, notice: 'Brand was successfully destroyed.'
    end

    private

    def set_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.require(:brand).permit(
        :name,
        :summary,
        :description,
        :industry,
        :logo,
        :thumbnail_photo
      )
    end
  end
end

app/views/admin/brands/_form.html.erb
<%= simple_form_for brand, url: brand.new_record? ? admin_brands_path : admin_brand_path(brand) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :summary %>
    <%= f.input :description %>
    <%= f.input :industry, as: :select, collection: Industry.all, input_html: { class: 'selectize' } %>
    <%= f.input :logo %>
    <%= f.input :thumbnail_photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>
<br>
<%= link_to 'Show', admin_brand_path(@brand) %> |
<%= link_to 'Back', admin_brands_path %>

app/views/admin/brands/index.html.erb
<h1>Manage Brands</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th>Description</th>
      <th>Industry</th>
      <th>Logo</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= brand.summary %></td>
        <td><%= brand.description %></td>
        <td><%= brand.industry %></td>
        <td>
          <% if brand.logo_url %>
            <img src="<%= brand.logo_url %>" width="50">
          <% else %>
            N/A
          <% end %>
        </td>
        <td>
          <% if brand.thumbnail_photo_url %>
            <img src="<%= brand.thumbnail_photo_url %>" width="50">
          <% else %>
            N/A
          <% end %>
        </td>
        <td><%= link_to 'Show', admin_brand_path(brand) %></td>
        <td><%= link_to 'Edit', edit_admin_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', admin_brand_path(brand), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= page_entries_info @brands %>
  <br>
  <%= paginate @brands %>
</div>

<br>

<%= link_to 'New Brand', new_admin_brand_path %>

app/views/admin/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>
<br>
<%= link_to 'Back', admin_brands_path %>

app/views/admin/brands/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @brand.summary %>
</p>

<p>
  <strong>Description:</strong>
  <%= @brand.description %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @brand.industry %>
</p>

<p>
  <strong>Logo:</strong>
  <% if @brand.logo_url %>
  <img src="<%= @brand.logo_url %>" width="100">
  <% else %>
    N/A
  <% end %>
</p>

<p>
  <strong>Thumbnail photo:</strong>
  <% if @brand.thumbnail_photo_url %>
  <img src="<%= @brand.thumbnail_photo_url %>" width="100">
  <% else %>
    N/A
  <% end %>
</p>

<%= link_to 'Edit', edit_admin_brand_path(@brand) %> |
<%= link_to 'Back', admin_brands_path %>