config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :listings, only: [:index, :show]

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'users', to: 'users#index'

  namespace :admin do
    resources :listings
    resources :brands
    resources :companies
    resources :deals
  end

  resource :profile, controller: :profile, only: [:show, :edit, :update]
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  summary         :text
#  description     :text
#  industry        :string
#  logo            :string
#  thumbnail_photo :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Company < ApplicationRecord
  mount_uploader :logo, CompanyLogoUploader
  mount_uploader :thumbnail_photo, CompanyThumbnailPhotoUploader

  has_and_belongs_to_many :listings
  has_and_belongs_to_many :deals

  validates :name,
            presence: true,
            length: { minimum: 2, maximum: 200 }
end

app/controllers/admin/companies_controller.rb
module Admin
  class CompaniesController < BaseController
    before_action :set_company, only: [:show, :edit, :update, :destroy]

    def index
      @companies = Company.order(id: :desc).page(params[:page])
    end

    def show
    end

    def new
      @company = Company.new
    end

    def edit
    end

    def create
      @company = Company.new(company_params)

      if @company.save
        redirect_to admin_company_path(@company), notice: 'Company was successfully created.'
      else
        render :new
      end
    end

    def update
      if @company.update(company_params)
        redirect_to admin_company_path(@company), notice: 'Company was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @company.destroy
      redirect_to admin_companies_url, notice: 'Company was successfully destroyed.'
    end

    private

    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(
        :name,
        :summary,
        :description,
        :industry,
        :logo,
        :thumbnail_photo,
        :year_founded,
        contacts_attributes: [
          :id,
          :first_name,
          :last_name,
          :phone_number,
          :email,
          :_destroy
        ]
      )
    end
  end
end

app/views/admin/companies/_form.html.erb
<%= simple_nested_form_for company, url: company.new_record? ? admin_companies_path : admin_company_path(company) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-12">
      <%= f.input :name %>
      <%= f.input :summary %>
      <%= f.input :description %>
      <%= f.input :industry, as: :select, collection: Industry.all, input_html: { class: 'selectize' } %>
      <%= f.input :logo %>
      <%= f.input :thumbnail_photo %>
    </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>
<br>
<%= link_to 'Show', admin_company_path(@company) %> |
<%= link_to 'Back', admin_companies_path %>

app/views/admin/companies/index.html.erb
<h1>Manage Companies</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th>Description</th>
      <th>Industry</th>
      <th>Logo</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.summary %></td>
        <td><%= company.description %></td>
        <td><%= company.industry %></td>
        <td>
          <% if company.logo_url %>
            <img src="<%= company.logo_url %>" width="50">
          <% else %>
            N/A
          <% end %>
        </td>
        <td>
          <% if company.thumbnail_photo_url %>
            <img src="<%= company.thumbnail_photo_url %>" width="50">
          <% else %>
            N/A
          <% end %>
        </td>
        <td><%= link_to 'Show', admin_company_path(company) %></td>
        <td><%= link_to 'Edit', edit_admin_company_path(company) %></td>
        <td><%= link_to 'Destroy', admin_company_path(company), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= page_entries_info @companies %>
  <br>
  <%= paginate @companies %>
</div>

<br>

<%= link_to 'New Company', new_admin_company_path %>

app/views/admin/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>
<br>
<%= link_to 'Back', admin_companies_path %>

app/views/admin/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @company.summary %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @company.industry %>
</p>

<p>
  <strong>Logo:</strong>
  <% if @company.logo_url %>
  <img src="<%= @company.logo_url %>" width="100">
  <% else %>
    N/A
  <% end %>
</p>

<p>
  <strong>Thumbnail photo:</strong>
  <% if @company.thumbnail_photo_url %>
  <img src="<%= @company.thumbnail_photo_url %>" width="100">
  <% else %>
    N/A
  <% end %>
</p>

<%= link_to 'Edit', edit_admin_company_path(@company) %> |
<%= link_to 'Back', admin_companies_path %>