config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :listings, only: [:index, :show]

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'users', to: 'users#index'

  namespace :admin do
    resources :listings
    resources :brands
    resources :companies
    resources :deals
  end

  resource :profile, controller: :profile, only: [:show, :edit, :update]
end

app/models/deal.rb
# == Schema Information
#
# Table name: deals
#
#  id              :integer          not null, primary key
#  title           :string           not null
#  teaser          :text
#  description     :text
#  thumbnail_photo :string
#  cover_photo     :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Deal < ApplicationRecord
  mount_uploader :thumbnail_photo, DealThumbnailPhotoUploader
  mount_uploader :cover_photo, DealCoverPhotoUploader

  has_many :options, class_name: DealOption, dependent: :destroy, inverse_of: :deal
  accepts_nested_attributes_for :options, allow_destroy: true

  has_and_belongs_to_many :brands
  has_and_belongs_to_many :companies

  validates :title,
            presence: true,
            length: { maximum: 200 }
end

app/controllers/admin/deals_controller.rb
module Admin
  class DealsController < BaseController
    before_action :set_deal, only: [:show, :edit, :update, :destroy]

    def index
      @deals = Deal.order(id: :desc).page(params[:page])
    end

    def show
    end

    def new
      @deal = Deal.new
    end

    def edit
    end

    def create
      @deal = Deal.new(deal_params)

      if @deal.save
        redirect_to admin_deal_path(@deal), notice: 'Deal was successfully created.'
      else
        render :new
      end
    end

    def update
      if @deal.update(deal_params)
        redirect_to admin_deal_path(@deal), notice: 'Deal was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @deal.destroy
      redirect_to admin_deals_url, notice: 'Deal was successfully destroyed.'
    end

    private

    def set_deal
      @deal = Deal.find(params[:id])
    end

    def deal_params
      params.require(:deal).permit(
        :title,
        :teaser,
        :description,
        :thumbnail_photo,
        :cover_photo,
        company_ids: [],
        brand_ids: [],
        options_attributes: [
          :id,
          :title,
          :details,
          :original_price,
          :deal_price,
          :_destroy
        ]
      )
    end
  end
end

app/views/admin/deals/_form.html.erb
<%= simple_nested_form_for deal, url: deal.new_record? ? admin_deals_path : admin_deal_path(deal) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :title %>
      <%= f.input :teaser %>
      <%= f.input :description, input_html: { class: 'wysiwyg-editor' } %>
      <%= f.input :thumbnail_photo %>
      <%= f.input :cover_photo %>
    </div>
    <div class="col-md-6">
      <%= f.input :company_ids, label: 'Companies', as: :select, include_hidden: false, collection: Company.select(:id, :name), input_html: { class: 'selectize', multiple: true } %>
      <%= f.input :brand_ids, label: 'Brands', as: :select, include_hidden: false, collection: Brand.select(:id, :name), input_html: { class: 'selectize', multiple: true } %>
      <div class="form-group" style="border: 1px solid #ccc; padding: 10px">
        <legend>Deal options</legend>
        <%= f.fields_for :options do |f_option|%>
          <div class="row">
            <div class="col-md-10">
              <%= f_option.input :title, label: false, placeholder: 'Title' %>
              <%= f_option.input :details, label: false, placeholder: 'Details' %>
              <%= f_option.input :original_price, label: false, placeholder: 'Original price' %>
              <%= f_option.input :deal_price, label: false, placeholder: 'Deal price' %>
            </div>
            <div class="col-md-2">
              <%= f_option.link_to_remove "Remove", class: 'text-danger' %>
            </div>
            <hr>
          </div>
        <% end %>
        <%= f.link_to_add "Add option", :options, class: 'btn btn-sm btn-default' %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>
<br>
<%= link_to 'Show', admin_deal_path(@deal) %> |
<%= link_to 'Back', admin_deals_path %>

app/views/admin/deals/index.html.erb
<h1>Manage Deals</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Teaser</th>
      <th>Thumbnail photo</th>
      <th>Cover photo</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= deal.title %></td>
        <td><%= deal.teaser %></td>
        <td>
          <% if deal.thumbnail_photo_url %>
            <img src="<%= deal.thumbnail_photo_url %>" width="50">
          <% else %>
            N/A
          <% end %>
        </td>
        <td>
          <% if deal.cover_photo_url %>
            <img src="<%= deal.cover_photo_url %>" width="50">
          <% else %>
            N/A
          <% end %>
        </td>
        <td><%= deal.created_at %></td>
        <td><%= link_to 'Show', admin_deal_path(deal) %></td>
        <td><%= link_to 'Edit', edit_admin_deal_path(deal) %></td>
        <td><%= link_to 'Destroy', admin_deal_path(deal), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= page_entries_info @deals %>
  <br>
  <%= paginate @deals %>
</div>
<br>
<%= link_to 'New Deal', new_admin_deal_path %>

app/views/admin/deals/new.html.erb
<h1>New Deal</h1>

<%= render 'form', deal: @deal %>
<br>
<%= link_to 'Back', admin_deals_path %>

app/views/admin/deals/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @deal.title %>
</p>

<p>
  <strong>Brands:</strong>
  <%= @deal.brands.map(&:name).join(', ') %>
</p>

<p>
  <strong>Companies:</strong>
  <%= @deal.companies.map(&:name).join(', ') %>
</p>

<p>
  <strong>Teaser:</strong>
  <%= @deal.teaser %>
</p>

<p>
  <strong>Description:</strong>
  <p><%= @deal.description.html_safe %></p>
</p>

<p>
  <strong>Thumbnail:</strong>
  <% if @deal.thumbnail_photo_url %>
    <img src="<%= @deal.thumbnail_photo_url %>" width="50">
  <% else %>
    N/A
  <% end %>
</p>

<p>
  <strong>Cover:</strong>
  <% if @deal.cover_photo_url %>
    <img src="<%= @deal.cover_photo_url %>" width="50">
  <% else %>
    N/A
  <% end %>
</p>
<p>
  <strong>Deal options</strong>
  <table class="table table-bordered">
      <thead>
        <tr>
          <th>Title</th>
          <th>Details</th>
          <th>Original Price</th>
          <th>Deal Price</th>
        </tr>
      </thead>
      <tbody>
        <% @deal.options.each do |option| %>
          <tr>
            <td><%= option.title %></td>
            <td><%= option.details %></td>
            <td><%= option.original_price %></td>
            <td><%= option.deal_price %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
</p>

<br>
<%= link_to 'Edit', edit_admin_deal_path(@deal) %> |
<%= link_to 'Back', admin_deals_path %>